version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      # present the params via docker env vars "-e"
      - cluster.name=docker-cluster
      - "path.repo=/usr/share/elasticsearch/backups"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # bind-mount conf "-v"
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch/data1:/usr/share/elasticsearch/data
      - ./elasticsearch/backups:/usr/share/elasticsearch/backups
    ports:
      - 9200:9200
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
